language: java

matrix:
  include:
    - os: linux-ppc64le # power queue name
      jdk:  openjdk8
    - os: linux         # Intel queue name
      jdk:  openjdk8
    - os: linux         # Intel queue name
      jdk:  openjdk11

# whitelist
branches:
  only:
    - master
    - "2.10"
